# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'messenger.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Messenger(object):
    def setupUi(self, Messenger):
        Messenger.setObjectName("Messenger")
        Messenger.resize(519, 585)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Messenger.sizePolicy().hasHeightForWidth())
        Messenger.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        Messenger.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Messenger)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.hl_hlun_hlp = QtWidgets.QHBoxLayout()
        self.hl_hlun_hlp.setObjectName("hl_hlun_hlp")
        self.hlun = QtWidgets.QHBoxLayout()
        self.hlun.setObjectName("hlun")
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")
        self.hlun.addWidget(self.usernameLabel)
        self.usernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.usernameEdit.setFont(font)
        self.usernameEdit.setObjectName("usernameEdit")
        self.hlun.addWidget(self.usernameEdit)
        self.hl_hlun_hlp.addLayout(self.hlun)
        self.verlical_line = QtWidgets.QFrame(self.centralwidget)
        self.verlical_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.verlical_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verlical_line.setObjectName("verlical_line")
        self.hl_hlun_hlp.addWidget(self.verlical_line)
        self.hlp = QtWidgets.QHBoxLayout()
        self.hlp.setObjectName("hlp")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.hlp.addWidget(self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.hlp.addWidget(self.passwordEdit)
        self.hl_hlun_hlp.addLayout(self.hlp)
        self.gridLayout.addLayout(self.hl_hlun_hlp, 1, 0, 1, 1)
        self.hl_usermessage = QtWidgets.QHBoxLayout()
        self.hl_usermessage.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.hl_usermessage.setObjectName("hl_usermessage")
        self.userMessage = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userMessage.sizePolicy().hasHeightForWidth())
        self.userMessage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.userMessage.setFont(font)
        self.userMessage.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.userMessage.setObjectName("userMessage")
        self.hl_usermessage.addWidget(self.userMessage)
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.hl_usermessage.addWidget(self.sendButton)
        self.gridLayout.addLayout(self.hl_usermessage, 4, 0, 1, 1)
        self.vl_title = QtWidgets.QVBoxLayout()
        self.vl_title.setObjectName("vl_title")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.vl_title.addWidget(self.titleLabel)
        self.gridLayout.addLayout(self.vl_title, 0, 0, 1, 1)
        self.allMessages = QtWidgets.QTextBrowser(self.centralwidget)
        self.allMessages.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allMessages.sizePolicy().hasHeightForWidth())
        self.allMessages.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.allMessages.setFont(font)
        self.allMessages.setObjectName("allMessages")
        self.gridLayout.addWidget(self.allMessages, 2, 0, 1, 1)
        self.horizont_line = QtWidgets.QFrame(self.centralwidget)
        self.horizont_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.horizont_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horizont_line.setObjectName("horizont_line")
        self.gridLayout.addWidget(self.horizont_line, 3, 0, 1, 1)
        self.gridLayout.setRowStretch(2, 20)
        self.gridLayout.setRowStretch(4, 1)
        Messenger.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Messenger)
        self.statusbar.setObjectName("statusbar")
        Messenger.setStatusBar(self.statusbar)

        self.retranslateUi(Messenger)
        QtCore.QMetaObject.connectSlotsByName(Messenger)

    def retranslateUi(self, Messenger):
        _translate = QtCore.QCoreApplication.translate
        Messenger.setWindowTitle(_translate("Messenger", "Python Messenger"))
        self.usernameLabel.setText(_translate("Messenger", "Username:"))
        self.passwordLabel.setText(_translate("Messenger", "Password:"))
        self.userMessage.setHtml(_translate("Messenger", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p></body></html>"))
        self.sendButton.setText(_translate("Messenger", "Send"))
        self.titleLabel.setText(_translate("Messenger", "Python Messenger"))
        self.allMessages.setHtml(_translate("Messenger", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Courier New\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt; font-weight:600;\"><br /></p></body></html>"))
